spring:
  application:
    name: sndshun-framework-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.45.144:3306/framework?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 12d8870390857f96
    hikari:
      pool-name: framework-mybatis
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 60000
      max-lifetime: 600000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: select 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #不序列化空属性
    default-property-inclusion: non_null
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: logic_delete
      #逻辑删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus-join:
  #是否打印 mybatis plus join banner 默认true
  banner: true
  #全局启用副表逻辑删除(默认true) 关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  #拦截器MappedStatement缓存(默认true)
  ms-cache: true
  #表别名(默认 t)
  table-alias: t
  #副表逻辑删除条件的位置，支持where、on
  #默认ON （1.4.7.2及之前版本默认为where）
  logic-del-type: on
server:
  compression:
    #开启gzip压缩
    enabled: true
    #压缩数据类型
    mime-types: application/json