/*
 Navicat Premium Data Transfer

 Source Server         : 华为云
 Source Server Type    : MySQL
 Source Server Version : 80023 (8.0.23)
 Source Host           : 124.70.45.144:3306
 Source Schema         : framework

 Target Server Type    : MySQL
 Target Server Version : 80023 (8.0.23)
 File Encoding         : 65001

 Date: 03/12/2023 12:52:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for template_model
-- ----------------------------
DROP TABLE IF EXISTS `template_model`;
CREATE TABLE `template_model`  (
  `id` bigint NOT NULL COMMENT 'id',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '模板名',
  `type` bigint NULL DEFAULT NULL COMMENT '模板类型',
  `context` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '模板内容',
  `preview` tinyblob NULL COMMENT '模板预览',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户号',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁',
  `logic_delete` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除;0：正常 1：删除',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '最后更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '模板主体;' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of template_model
-- ----------------------------
INSERT INTO `template_model` VALUES (1725304864293183489, '欢迎来到本站', 1, '<!DOCTYPE html> <html lang=\"zh-CN\"> <head> <meta charset=\"UTF-8\"> <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> <title>欢迎加入我们的站点</title> <style> body { font-family: \'Microsoft YaHei\', Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; height: 100vh; } .container { max-width: 600px; background-color: #fff; padding: 40px; border-radius: 5px; box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); animation: fadeInUp 1s ease-out; } h1 { color: #333; margin-bottom: 20px; animation: scaleIn 1s ease-out; } p { color: #555; margin-bottom: 20px; } .button { display: inline-block; padding: 10px 20px; font-size: 16px; text-align: center; text-decoration: none; background-color: #4caf50; color: #fff; border-radius: 5px; transition: background-color 0.3s ease-out; } .button:hover { background-color: #45a049; } @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } } @keyframes scaleIn { from { transform: scale(0.8); } to { transform: scale(1); } } </style> </head> <body> <div class=\"container\"> <h1>欢迎加入我们的站点！${name!\"\"}</h1> <p>感谢您加入我们的社区。我们非常期待您的加入。</p> <p>探索我们的网站，发现令人惊奇的内容和功能。</p> <p>如果您有任何问题或需要帮助，请随时与我们联系。</p> <a href=\"https://www.baidu.com\" class=\"button\">立即探索</a> </div> </body> </html>', NULL, NULL, 0, 0, NULL, '2023-11-17 08:08:29', NULL, '2023-11-17 08:08:29');
INSERT INTO `template_model` VALUES (1729587620841947138, '欢迎来到本站', 1, '<!DOCTYPE html> <html lang=\"zh-CN\"> <head> <meta charset=\"UTF-8\"> <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> <title>欢迎加入我们的站点</title> <style> body { font-family: \'Microsoft YaHei\', Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; height: 100vh; } .container { max-width: 600px; background-color: #fff; padding: 40px; border-radius: 5px; box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); animation: fadeInUp 1s ease-out; } h1 { color: #333; margin-bottom: 20px; animation: scaleIn 1s ease-out; } p { color: #555; margin-bottom: 20px; } .button { display: inline-block; padding: 10px 20px; font-size: 16px; text-align: center; text-decoration: none; background-color: #4caf50; color: #fff; border-radius: 5px; transition: background-color 0.3s ease-out; } .button:hover { background-color: #45a049; } @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } } @keyframes scaleIn { from { transform: scale(0.8); } to { transform: scale(1); } } </style> </head> <body> <div class=\"container\"> <h1>欢迎加入我们的站点！${name!\"\"}</h1> <p>感谢您加入我们的社区。我们非常期待您的加入。</p> <p>探索我们的网站，发现令人惊奇的内容和功能。</p> <p>如果您有任何问题或需要帮助，请随时与我们联系。</p> <a href=\"https://www.baidu.com\" class=\"button\">立即探索</a> </div> </body> </html>', NULL, NULL, 0, 0, NULL, '2023-11-29 03:46:38', NULL, '2023-11-29 03:46:38');
INSERT INTO `template_model` VALUES (1729587657399480321, '欢迎来到本站', 1, '<!DOCTYPE html>\r\n<html lang=\"zh-CN\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>欢迎加入我们的站点</title>\r\n    <style>\r\n        body {\r\n            font-family: \'Microsoft YaHei\', Arial, sans-serif;\r\n            background-color: #f4f4f4;\r\n            margin: 0;\r\n            padding: 0;\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            height: 100vh;\r\n        }\r\n\r\n        .container {\r\n            max-width: 600px;\r\n            background-color: #fff;\r\n            padding: 40px;\r\n            border-radius: 5px;\r\n            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n            animation: fadeInUp 1s ease-out;\r\n        }\r\n\r\n        h1 {\r\n            color: #333;\r\n            margin-bottom: 20px;\r\n            animation: scaleIn 1s ease-out;\r\n        }\r\n\r\n        p {\r\n            color: #555;\r\n            margin-bottom: 20px;\r\n        }\r\n\r\n        .button {\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            font-size: 16px;\r\n            text-align: center;\r\n            text-decoration: none;\r\n            background-color: #4caf50;\r\n            color: #fff;\r\n            border-radius: 5px;\r\n            transition: background-color 0.3s ease-out;\r\n        }\r\n\r\n        .button:hover {\r\n            background-color: #45a049;\r\n        }\r\n\r\n        @keyframes fadeInUp {\r\n            from {\r\n                opacity: 0;\r\n                transform: translateY(20px);\r\n            }\r\n            to {\r\n                opacity: 1;\r\n                transform: translateY(0);\r\n            }\r\n        }\r\n\r\n        @keyframes scaleIn {\r\n            from {\r\n                transform: scale(0.8);\r\n            }\r\n            to {\r\n                transform: scale(1);\r\n            }\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n<div class=\"container\">\r\n    <h1>欢迎加入我们的站点！${name!\"\"}</h1>\r\n    <p>感谢您加入我们的社区。我们非常期待您的加入。</p>\r\n    <p>探索我们的网站，发现令人惊奇的内容和功能。</p>\r\n    <p>如果您有任何问题或需要帮助，请随时与我们联系。</p>\r\n    <a href=\"https://www.baidu.com\" class=\"button\">立即探索</a>\r\n</div>\r\n</body>\r\n</html>', NULL, NULL, 0, 0, NULL, '2023-11-29 03:46:46', NULL, '2023-11-29 03:46:46');
INSERT INTO `template_model` VALUES (1729592887075926018, '欢迎来到本站', 1, '<!DOCTYPE html> <html lang=\"zh-CN\"> <head> <meta charset=\"UTF-8\"> <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> <title>欢迎加入我们的站点</title> <style> body { font-family: \'Microsoft YaHei\', Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; height: 100vh; } .container { max-width: 600px; background-color: #fff; padding: 40px; border-radius: 5px; box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); animation: fadeInUp 1s ease-out; } h1 { color: #333; margin-bottom: 20px; animation: scaleIn 1s ease-out; } p { color: #555; margin-bottom: 20px; } .button { display: inline-block; padding: 10px 20px; font-size: 16px; text-align: center; text-decoration: none; background-color: #4caf50; color: #fff; border-radius: 5px; transition: background-color 0.3s ease-out; } .button:hover { background-color: #45a049; } @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } } @keyframes scaleIn { from { transform: scale(0.8); } to { transform: scale(1); } } </style> </head> <body> <div class=\"container\"> <h1>欢迎加入我们的站点！${name!\"\"}</h1> <p>感谢您加入我们的社区。我们非常期待您的加入。</p> <p>探索我们的网站，发现令人惊奇的内容和功能。</p> <p>如果您有任何问题或需要帮助，请随时与我们联系。</p> <a href=\"https://www.baidu.com\" class=\"button\">立即探索</a> </div> </body> </html>', NULL, NULL, 0, 0, NULL, '2023-11-29 04:07:34', NULL, '2023-11-29 04:07:34');
INSERT INTO `template_model` VALUES (1729592914372358146, '欢迎来到本站', 1, '<!DOCTYPE html>\r\n<html lang=\"zh-CN\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>欢迎加入我们的站点</title>\r\n    <style>\r\n        body {\r\n            font-family: \'Microsoft YaHei\', Arial, sans-serif;\r\n            background-color: #f4f4f4;\r\n            margin: 0;\r\n            padding: 0;\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            height: 100vh;\r\n        }\r\n\r\n        .container {\r\n            max-width: 600px;\r\n            background-color: #fff;\r\n            padding: 40px;\r\n            border-radius: 5px;\r\n            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n            animation: fadeInUp 1s ease-out;\r\n        }\r\n\r\n        h1 {\r\n            color: #333;\r\n            margin-bottom: 20px;\r\n            animation: scaleIn 1s ease-out;\r\n        }\r\n\r\n        p {\r\n            color: #555;\r\n            margin-bottom: 20px;\r\n        }\r\n\r\n        .button {\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            font-size: 16px;\r\n            text-align: center;\r\n            text-decoration: none;\r\n            background-color: #4caf50;\r\n            color: #fff;\r\n            border-radius: 5px;\r\n            transition: background-color 0.3s ease-out;\r\n        }\r\n\r\n        .button:hover {\r\n            background-color: #45a049;\r\n        }\r\n\r\n        @keyframes fadeInUp {\r\n            from {\r\n                opacity: 0;\r\n                transform: translateY(20px);\r\n            }\r\n            to {\r\n                opacity: 1;\r\n                transform: translateY(0);\r\n            }\r\n        }\r\n\r\n        @keyframes scaleIn {\r\n            from {\r\n                transform: scale(0.8);\r\n            }\r\n            to {\r\n                transform: scale(1);\r\n            }\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n<div class=\"container\">\r\n    <h1>欢迎加入我们的站点！${name!\"\"}</h1>\r\n    <p>感谢您加入我们的社区。我们非常期待您的加入。</p>\r\n    <p>探索我们的网站，发现令人惊奇的内容和功能。</p>\r\n    <p>如果您有任何问题或需要帮助，请随时与我们联系。</p>\r\n    <a href=\"https://www.baidu.com\" class=\"button\">立即探索</a>\r\n</div>\r\n</body>\r\n</html>', NULL, NULL, 0, 0, NULL, '2023-11-29 04:07:40', NULL, '2023-11-29 04:07:40');

SET FOREIGN_KEY_CHECKS = 1;
