spring:
  profiles:
    active: @profiles.active@

oss:
  enabled: true
  type: MINIO
  endpoint: http://124.70.45.144:9000
  access-key: gGjKMK90pnVyEk6zAWRn
  secret-key: H99GsEl0MQy0MyCYLOfzugcRH6Dv0Wz9Gkskl84a
  default-bucket-name: test