spring:
  redis:
    host:

system:
  doubleCache:
    allowNull: false  #是否可缓存 Null
    #caffeine 初始缓存数量
    init: 128
    #caffeine 最大缓存数量
    max: 1024
    #Caffeine过期时间单位秒 基于最后访问时间  7天
    caffeineExpire: 604800
    #Redis缓存过期时间单位秒 14天
    redisExpire: 1209600